services:
    - postgresql
    - mysql

language: perl6

perl6:
    - 2016.01
    - latest
sudo: false
install:
    - rakudobrew build-panda
    - panda install .
before_install:
    # mysql
    - mysql -e "CREATE DATABASE dbdishtest;" -uroot
    - mysql -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'testpass';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON dbdishtest.* TO 'testuser'@'localhost';" -uroot
    # Pg
    - psql -c 'CREATE DATABASE dbdishtest;' -U postgres
